name: serverpod_vps
description: A CLI tool for generating and managing Serverpod VPS deployments and configurations
version: 0.0.1
repository: https://github.com/inf0rmatix/serverpod_vps
homepage: https://github.com/inf0rmatix/serverpod_vps
documentation: https://github.com/inf0rmatix/serverpod_vps
topics:
  - serverpod
  - vps
  - serverpod-vps

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.6.0
  path: ^1.9.1
  mason_logger: ^0.3.2
  meta: ^1.9.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15

executables:
  serverpod_vps: serverpod_vps

platforms:
  linux:
  macos:
  windows:

assets:
  - assets/default.env
  - assets/templates/serverpod_templates/
  - assets/templates/serverpod_templates/github/workflows/
  - assets/templates/serverpod_templates/projectname_server/
  - assets/templates/serverpod_templates/projectname_server_upgrade/
