name: serverpod_vps
description: A CLI tool for generating and managing Serverpod VPS deployments and configurations
version: 1.0.0
repository: https://github.com/inf0rmatix/serverpod_vps
homepage: https://github.com/inf0rmatix/serverpod_vps
documentation: https://github.com/inf0rmatix/serverpod_vps
topics:
  - serverpod
  - vps
  - serverpod-vps

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.6.0
  path: ^1.9.1
  mason_logger: ^0.3.2

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15

executables:
  serverpod_vps: main

platforms:
  linux:
  macos:
  windows:
